name: Tests

on: push

jobs:
  lint:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: make install
      - name: Run tests & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make tests-coverage
          coverageLocations: |
            ${{github.workspace}}/logs/coverage.xml:clover
          debug: true  